---
title: "A Novice Analysis of the Words in Harry Potter"
author: "Evan Musick"
date: "January 30, 2018"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading in the Text

I found someone who has kindly provided access to the entire text of each Harry Potter book. The data can be accessed [here](https://github.com/bradleyboehmke/harrypotter). Each book is a character vector - one for each chapter.

```{r message=FALSE}
library(harrypotter)
library(tidyverse)
library(tidytext)
library(stringr)
library(knitr)

books <- list("Sorcerer's Stone" = philosophers_stone, "Chamber of Secrets" = chamber_of_secrets, 
              "Prisoner of Azkaban" = prisoner_of_azkaban, "Goblet of Fire" = goblet_of_fire, 
              "Order of the Phoenix" = order_of_the_phoenix, "Half-Blood Prince" = half_blood_prince,
              "Deathly Hallows" = deathly_hallows)

process_text <- function(book_title, books){
  book_text_raw <- tibble(books[[book_title]]) %>%
    select(text = 1) %>%
    mutate(chapter = row_number(),
           book = book_title) %>%
  unnest_tokens(word, text)
}

all_books_raw <- bind_rows(lapply(names(books), process_text, books)) %>%
  mutate(book = factor(book, levels = unique(book)))

```
This gives us one word per row with identifiers for the book and chapter.
```{r echo = FALSE}
all_books_raw
```

```{r}
characters <- c("harry", "ron", "hermione", "dumbledore")

all_books_raw %>%
  count(book, word) %>%
  mutate(freq_by_book = n/sum(n)) %>%
  filter(word %in% characters) %>%
  ggplot(aes(x = book, y = freq_by_book)) + 
  geom_bar(stat = "identity") +
  facet_wrap(~word,  scales = "free") +
  scale_x_discrete(limits = rev(levels(all_books_raw$book))) + 
  coord_flip() +
  theme_bw()


```


